---
params:
  district: 70
  district_name: "District Name"
  report_date: !r format(lubridate::today(), "%B %d, %Y")
  data_file_date: !r lubridate::today()
title: "`r stringr::str_c('Monthly DPSIG/SLIG Data Report for ', params$district_name)`"
date: "`r params$report_date`"
output: pdf_document
classoption: landscape
---

```{r setup, include=FALSE}

library(knitr)
library(gridExtra)
library(magrittr)
library(openxlsx)
library(tidyverse)

directory_onedrive <- "C:/Users/CA20397/OneDrive - TN Dept of Education/"
directory_project <- "goals/dsi-grant-monitoring/2020-dpsig-slig-monitoring/"

opts_chunk$set(
  echo = F,
  # fig.height = 5,
  # fig.width = 8,
  message = F,
  results = "hide",
  warning = F
)

opts_knit$set(root.dir = str_c(directory_onedrive, directory_project))

```

```{r data, include=FALSE}

absence_district_month <-
  read_csv(
    str_c("data/absence-district-month-",
          params$data_file_date,
          ".csv")
  )

absence_school <-
  read_csv(
    str_c("data/absence-school-",
          params$data_file_date,
          ".csv")
  )

discipline_district_month <-
  read_csv(
    str_c("data/discipline-district-month-",
          params$data_file_date,
          ".csv")
  )

discipline_school <-
  read_csv(
    str_c("data/discipline-school-",
          params$data_file_date,
          ".csv")
  )

schools_csi <- read_csv("data/schools-csi.csv")

```

```{r graph_1, include=FALSE}

graph_1 <-
  pmap(
    .l = list(
      "data_frames" = list(absence_school, discipline_school),
      "y_variables" = quos(
        pct_students_chr_absent_2020_ytd,
        pct_students_disciplined_2020_ytd
      ),
      "y_variables_2" = c(
        "pct_students_chr_absent_2020_ytd",
        "pct_students_disciplined_2020_ytd"
      ),
      "y_labels" = c("Chronically Absent", "Disciplined"),
      "fill_colors" = c("red", "orange")
    ),
    .f = ~ ..1 %>%
      left_join(schools_csi, by = c("district", "school")) %>%
      mutate(
        school_name = reorder(school_name, !! ..2, max),
        in_district = district == params$district
      ) %>%
      mutate_at(..3, funs(if_else(. == 0, 0.1, .))) %>%
      ggplot(aes(x = school_name, y = !! ..2)) +
      geom_col(aes(fill = in_district)) +
      scale_x_discrete(name = "Each bar represents one CSI school.") +
      scale_y_continuous(
        name = str_c("Percent of Students ", ..4, " This Year")
      ) +
      scale_fill_manual(
        name = "School in your district?",
        labels = c("No", "Yes"),
        values = c("gray", ..5)
      ) +
      theme_minimal() +
      theme(
        axis.text.x = element_blank(),
        legend.position = "top"
      ) +
      ggtitle("Your CSI Schools Compared to Other Districts'")
  ) %>%
  set_names(nm = c("absence", "discipline"))

```
