select
  isp.school_year + 1 as year,
  sch.district_no as system,
  dst.district_name as system_name,
  sch.school_no as school,
  sch.school_name,
  igr.assignment as grade,
  isp.isp_id,
  isp.student_key as state_id,
  isp.local_system_key as local_id,
  isp.last_name,
  isp.first_name,
  STN.GENDER,
  STN.ETHNIC_ORIGIN AS RACE,
  STN.ETHNICITY AS HISPANIC,
  NVL(CLA.ED, 0) AS ED,
  CLA.classification,
  NVL(SPD.SWD, 0) AS SWD,
  SPD.PRIMARY_DIS,
  ELB.ENGLISH_LANGUAGE_DESCR AS ELB,
  ISP.BEGIN_DATE,
  ISP.END_DATE,
  (SELECT COUNT(DISTINCT CAL.ID_DATE)
    FROM SCAL_ID_DAYS CAL
    WHERE
      ISP.SCHOOL_YEAR = CAL.SCHOOL_YEAR
      AND ISP.SCHOOL_BU_ID = CAL.SCHOOL_BU_ID
      AND ISP.INSTRUCTIONAL_PROGRAM_NUM = CAL.INSTRUCTIONAL_PROGRAM_NUM
      AND ISP.BEGIN_DATE <= CAL.ID_DATE
      AND (ISP.END_DATE > CAL.ID_DATE
        OR ISP.END_DATE IS NULL and sysdate > cal.id_date)
  ) AS DAYS_ENROLLED,
  CLA.SC_BEGIN_DATE,
  CLA.SC_END_DATE,
  (SELECT COUNT(DISTINCT CAL.ID_DATE)
    FROM SCAL_ID_DAYS CAL
    WHERE
      ISP.SCHOOL_YEAR = CAL.SCHOOL_YEAR
      AND ISP.SCHOOL_BU_ID = CAL.SCHOOL_BU_ID
      AND ISP.INSTRUCTIONAL_PROGRAM_NUM = CAL.INSTRUCTIONAL_PROGRAM_NUM
      AND CLA.SC_BEGIN_DATE <= CAL.ID_DATE
      AND (CLA.SC_END_DATE > CAL.ID_DATE
        OR CLA.SC_END_DATE IS NULL)
  ) AS DAYS_WITH_SC,
  SPD.DIS_BEGIN_DATE,
  SPD.DIS_END_DATE,
  (SELECT COUNT(DISTINCT CAL.ID_DATE)
    FROM SCAL_ID_DAYS CAL
    WHERE
      ISP.SCHOOL_YEAR = CAL.SCHOOL_YEAR
      AND ISP.SCHOOL_BU_ID = CAL.SCHOOL_BU_ID
      AND ISP.INSTRUCTIONAL_PROGRAM_NUM = CAL.INSTRUCTIONAL_PROGRAM_NUM
      AND SPD.DIS_BEGIN_DATE <= CAL.ID_DATE
      AND (SPD.DIS_END_DATE > CAL.ID_DATE
        OR SPD.DIS_END_DATE IS NULL)
  ) AS DAYS_WITH_DIS
FROM
  INSTRUCTIONAL_SERVICE_PERIOD ISP
  JOIN SCHOOL SCH ON ISP.SCHOOL_BU_ID = SCH.SCHOOL_BU_ID
  join district dst on sch.district_no = dst.district_no
  join instructional_grade igr on isp.isp_id = igr.isp_id
  JOIN STUDENT_NEW STN ON ISP.STUDENT_KEY = STN.STUDENT_KEY
  FULL JOIN (
    SELECT
      ISP_ID,
      student_classification_type as classification,
      (CASE
        WHEN STUDENT_CLASSIFICATION_TYPE IN ('H', 'I', 'J', 'U', 'FOS01')
        THEN 1
        ELSE 0
        END
      ) AS ED,
      SC_BEGIN_DATE,
      SC_END_DATE
    FROM STUDENT_CLASSIFICATION
  ) CLA ON ISP.ISP_ID = CLA.ISP_ID
FULL JOIN (
  SELECT
    SPDI.ISP_ID,
    1 AS SWD,
    DSC.DISABILITY_TYPE_DESCR AS PRIMARY_DIS,
    SPDI.DIS_BEGIN_DATE,
    SPDI.DIS_END_DATE
  FROM
    SPED_DISABILITIES SPDI
    JOIN DISABILITY_CODES DSC
      ON SPDI.DISABILITY_TYPE = DSC.DISABILITY_TYPE
  WHERE
    SPDI.DISABILITY_LEVEL = 'P'
) SPD ON ISP.ISP_ID = SPD.ISP_ID
LEFT JOIN ENGLISH_LANGUAGE_BACKGROUND ELB ON
  ISP.ENGLISH_LANGUAGE_BACKGROUND = ELB.ENGLISH_LANGUAGE_BACKGROUND
WHERE
  ISP.TYPE_OF_SERVICE = 'P'
